# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8072576861ec61177fcf77d681fe7b33caae7e2660dda59dbdd1aa4f729f85031ef6e5e7ac9a34ae0bbb5459599bdec08729b9d4c62e2288f6a27120e9272e18

test:
  secret_key_base: 89ef89191b978c37ada7c17b13299e3bb630a3ed1e0871a43b89b835277c3e4ef7c67d55b4e95e869162ca4b5343e07d4f25ce781cebb8ccead250989adba05f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
